package com.mac242.guerradasuniversidades.core.modelo;
public enum Estrutura {
	SALA_AULA, PROFESSOR, ALUNO, BANDEJAO, SETOR_DADOS, PRACA_CENTRAL,
	CENTRO_ESPORTES, AUMENTO_SALARIAL, CHURRASCO_DEBATE, FESTA, SOBREMESA_BANDEJAO,
	SEMINARIO, GUARDA_UNIVERSITARIA;
}
